name: ingrained
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  cloud_firestore: ^5.6.3
  firebase_core: ^3.11.0
  intl: ^0.19.0
  firebase_database: ^11.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_field: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.2.11

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/ingrainedLogo.png"
  android: true
  ios: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ingrainedLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/ingrainedLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/ingrainedLogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/ingrainedLogo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/