// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiM8ImXB5TWwjmgdvrHnbZFeVjmeRRC2I',
    appId: '1:873430311197:web:e122bb18b80c24480101f4',
    messagingSenderId: '873430311197',
    projectId: 'ingrained',
    authDomain: 'ingrained.firebaseapp.com',
    storageBucket: 'ingrained.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp7IQ2P_Fq4bU-KZ2g-7vSHs11yOOD5fc',
    appId: '1:873430311197:android:3000922cb7c0231f0101f4',
    messagingSenderId: '873430311197',
    projectId: 'ingrained',
    storageBucket: 'ingrained.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs48pjVZPZKf8SpuaZiMTg0ytcyKex07k',
    appId: '1:873430311197:ios:e4fad264c4cbba570101f4',
    messagingSenderId: '873430311197',
    projectId: 'ingrained',
    storageBucket: 'ingrained.firebasestorage.app',
    iosBundleId: 'com.example.ingrained',
  );

}